export default {
  FCART_ITEMS_LOADING: 'FCART_ITEMS_LOADING',
  FCART_ITEMS_SUCCESS: 'FCART_ITEMS_SUCCESS',
  FCART_ITEMS_ERROR: 'FCART_ITEMS_ERROR',
  UPDATE_CART_ITEM: 'UPDATE_CART_ITEM',
  DELETE_CART_ITEM: 'DELETE_CART_ITEM',
};
